### ISSUE TITLE
Can't make this work

### ISSUE THREAD

**Issue by Emyrarall** [webguerilla/joomla-html5audio#2]
I've tried all the different permutations of the shortcode but cannot get my mp3 files to stream. I'd really like to get this to work as I have a large site with rapid1 pixelout code used to embed audio on most pages. Are you aware of another player that uses the same code?

**Comment by marcobeierer** [comment]
Sorry, I don't know another player.

Could you describe your issue in more detail? What is the error you are getting or what does not work? Could you send me a link to your page?

**Comment by Emyrarall** [comment]
Hi Marco,
Thanks for such a prompt reply - much appreciated.
I have a joomla site here - www.traciaucymraeg.com
The installation is actually in a subdirectory - swn3
My audio files are in this subdirectory in a folder called pobmp3
so for instance one of the tracks I'm trying to set up is called Hen Hen Hanes and I can stream it straight from a browser by entering the following address
www.traciaucymraeg.com/swn3/pobmp3/Hen Hen Hanes.mp3
I've set up pobmp3 as my basepath (see screenshot)
![screen shot 2017-07-21 at 18 35 55](https://user-images.githubusercontent.com/30350272/28475548-a8ac8d22-6e44-11e7-8f95-fba69b80c5e3.png)

and I've entered what I think ought to be the right shortcode against track 3 of the listing , with the following line:
{audio}Hen Hen Hanes.mp3{/audio}
But it doesn't seem to be able to find the mp3 file. It's the 3rd track in the listing at this address:
[http://www.traciaucymraeg.com/swn3/en/artistiaid-artists/87-john-ac-alun/104-hir-a-hwyr
![screen shot 2017-07-21 at 18 35 55](https://user-images.githubusercontent.com/30350272/28475420-00cd2094-6e44-11e7-8c3f-9d9970ea2b9b.png)](url)
The first two tracks are working with another plug in that uses a different shortcode. I prefer the way you're player looks - simple and clean.
As you can probably tell, I'm not a programmer but a musician that's keen to learn!
Regards - Emyr

**Comment by marcobeierer** [comment]
Hi Emyr

the base path should be `popmp3/` instead of `popmp3`.

However, I'm not sure if this solves all problems, because the link currently looks strange and it tries to load a file called `Cysur.mp3`.

Could you change the base path and report back, so that I could have a second look as soon as it is set?

If it does not work, do you currently use other plugins that also use the `{audio}` tag?

**Comment by Emyrarall** [comment]
Marco,
That's solved it. I was messing with the link since sending you the last email which is why it was pointing to a different mp3 file. It's all good. I thought that I'd tried some  /'s as well, but all the stars are in alignment now! Thanks so much for your little plug in - saved me a lot of grief.
I've book marked your site, ready for when I win that first Grammy.
Regards - Emyr

**Comment by marcobeierer** [comment]
Hi Emyr,

I'm glad that it works now and the plugin saved you some time. I wish you further much success and hopefully the first Grammy is not too far away :1st_place_medal: :smile: 

Best regards,
Marco
